



<html>
<head>
<title>Documento sin t&iacute;tulo</title>
</head>
<LINK href="../archivos/css_ref_web.css" rel=stylesheet type=text/css>
<LINK href="../archivos/home-ie6.css" type=text/css rel=stylesheet>
<body>
<form action="" method="post" name="form1">
<TABLE width="100%" align="center" cellPadding=0 cellSpacing=0 class="cm lbl">
 <TBODY>
      <TR  vAlign=top  class=dt>  
        <TD width="90%" vAlign=bottom colspan=3> <H4>Calidad Fisica y Quimica 
            C&aacute;todos Comerciales</H4></TD>
        <TD  width="10%" vAlign=bottom><div align="right"><img src="../archivos/imprimir.gif" width="26" height="18"></div></TD>
      </TR>
      <TR class=lcol vAlign=top> 
        <TD colSpan=6 bgcolor="#0066CC"> 
         <TABLE width="100%" border=0 cellPadding=2 cellSpacing=2>
          <TBODY>
            <TR class=lcol> 
          <td width="90" align="center"><div align="center"><font size="6"><strong>GRUPO</strong></font></div></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Ag</strong></font></div></p><div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Au</strong></font></div></p><div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="58" align="center"><div align="center"><font size="6"><strong>As</strong></font></div></p><div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Sb</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Zn</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>S</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Bi</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Sn</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Fe</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Ni</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Pb</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Se</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>Te</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
          <td width="48" align="center"><div align="center"><font size="6"><strong>O</strong></font></div></p>                    <div align="center"><font size="6"><strong>ppm</strong></font></div></p></td>
        </tr>
            <TR class=lcol> 
			<td align='center'>05&nbsp</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
		</tr>
            <TR class=lcol> 
			<td align='center'>05&nbsp</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
		</tr>
            <TR class=lcol> 
			<td align='center'>05&nbsp</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
		</tr>
            <TR class=lcol> 
			<td align='center'>05&nbsp</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
		</tr>
            <TR class=lcol> 
			<td align='center'>05&nbsp</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
		</tr>
            <TR class=lcol> 
			<td align='center'>05&nbsp</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
			<td align='center'>&nbsp;</td>
            </TR>
          </TBODY>
        </TABLE>
            </TD>
      </TR>
    </TBODY>
  </TABLE>
  
  <p>&nbsp; </p>

<TABLE width="100%" align="center" cellPadding=0 cellSpacing=0 class="cm lbl">
 <TBODY>
      <TR  vAlign=top  class=dt>  
        <TD width="90%" vAlign=bottom colspan=3> <H4><B>Renovaci&oacute;n 
            de Electrodos</B></H4></TD>
        <TD  width="10%" vAlign=bottom><div align="right"><img src="../archivos/imprimir.gif" width="26" height="18"></div></TD>
      </TR>
      <TR class=lcol vAlign=top> 
        <TD colSpan=6 bgcolor="#0066CC"> 
         <TABLE width="100%" border=0 cellPadding=2 cellSpacing=2>
          <TBODY>

           <TR class=lcol>  
                  <td width="12%" rowspan="2" ><div align="center"><font size="6"><strong>CIRCUITO</strong></font></div></td>
                  <td width="9%" rowspan="2" ><div align="center"><font size="6"><strong>GRUPO</strong></font></div></td>
                  <td colspan="2" ><div align="center"><font size="6"><strong>TIPO DE ANODOS</strong></font></div></td>
                  <td colspan="8" ><div align="center"><font size="6"><strong>COMPOSICION ANODO NUEVO (PPM)</strong></font></div></td>
          </tr>
            <TR class=lcol>  
                  <td width="8%" height="27" align="center"><div align="center"><font size="6"><strong>SEMI</strong></font></div></td>
                  <td width="8%" align="center"><div align="center"><font size="6"><strong>NUEVO</strong></font></div></td>
                  <td width="8%" align="center"><p><div align="center"><font size="6"><strong>As</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;1500</strong></font></div></p></td>
                  <td width="10%" align="center"><p><div align="center"><font size="6"><strong>Sb</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;500</strong></font></div></p></td>
                  <td width="10%" align="center"><p><div align="center"><font size="6"><strong>Bi</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;15</strong></font></div></p></td>
                  <td width="7%" align="center"><p><div align="center"><font size="6"><strong>Te</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;50</strong></font></div></p></td>
                  <td width="8%" align="center"><p><div align="center"><font size="6"><strong>O</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;2000</strong></font></div></p></td>
                  <td width="9%" align="center"><p><div align="center"><font size="6"><strong>Se</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;300</strong></font></div></p></td>
                  <td width="5%" align="center"><p><div align="center"><font size="6"><strong>Fe</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;30</strong></font></div></p></td>
                  <td width="6%" align="center"><p><div align="center"><font size="6"><strong>Ni</strong></font></div></p>                    <div align="center"><font size="6"><strong>&lt;150</strong></font></div></p></td>
          </tr>
            <TR class=lcol> 
                <td align='center'>01&nbsp</td>
                <td align='center'>05&nbsp</td>
                <td align='center'>HVL&nbsp</td>
                <td align='center' ><font color='blue'><a href="JavaScript:detalle_anodos('2004-01-01','5')">HVL</a></font></td>
                <td align='center'> 830&nbsp</td>
                <td align='center'> 213&nbsp</td>
                <td align='center'> 10&nbsp</td>
                <td align='center'> 18&nbsp</td>
                <td align='center'> 1179&nbsp</td>
                <td align='center'> 105&nbsp</td>
                <td align='center'><font color='red'><strong> 34&nbsp</strong></font></td>
                <td align='center'><font color='red'><strong> 452&nbsp</strong></font></td>
          </tr>
            <TR class=lcol> 
                <td align='center'>02&nbsp</td>
                <td align='center'>14&nbsp</td>
                <td align='center'>Ventana&nbsp</td>
                <td align='center' ><font color='blue'><a href="JavaScript:detalle_anodos('2004-01-01','14')">Ventana</a></font></td>
                <td align='center'> 1085&nbsp</td>
                <td align='center'> 264&nbsp</td>
                <td align='center'> 4&nbsp</td>
                <td align='center'> 15&nbsp</td>
                <td align='center'> 1773&nbsp</td>
                <td align='center'> 164&nbsp</td>
                <td align='center'><font color='red'><strong> 32&nbsp</strong></font></td>
                <td align='center'> 129&nbsp</td>
          </tr>
            <TR class=lcol> 
                <td align='center'>03&nbsp</td>
                <td align='center'>21&nbsp</td>
                <td align='center'>Ventana&nbsp</td>
                <td align='center' ><font color='blue'><a href="JavaScript:detalle_anodos('2004-01-01','21')">Ventana</a></font></td>
                <td align='center'> 1091&nbsp</td>
                <td align='center'> 264&nbsp</td>
                <td align='center'> 6&nbsp</td>
                <td align='center'> 16&nbsp</td>
                <td align='center'> 1465&nbsp</td>
                <td align='center'> 178&nbsp</td>
                <td align='center'><font color='red'><strong> 43&nbsp</strong></font></td>
                <td align='center'><font color='red'><strong> 152&nbsp</strong></font></td>
          </tr>
            <TR class=lcol> 
				<td align='center'>04&nbsp</td>
				<td align='center'>25&nbsp</td>
				<td align='center'>HVL&nbsp</td>
				<td align='center' ><font color='blue'><a href="JavaScript:detalle_anodos('2004-01-01','25')">HVL</a></font></td>
				<td align='center'> 841&nbsp</td>
				<td align='center'> 192&nbsp</td>
				<td align='center'> 11&nbsp</td>
				<td align='center'> 23&nbsp</td>
				<td align='center'> 1222&nbsp</td>
				<td align='center'> 121&nbsp</td>
				<td align='center'><font color='red'><strong> 32&nbsp</strong></font></td>
				<td align='center'><font color='red'><strong> 483&nbsp</strong></font></td>
         </tr>
         <TR class=lcol> 
				<td align='center'>05&nbsp</td>
				<td align='center'>34&nbsp</td>
				<td align='center'>Teniente&nbsp</td>
				<td align='center' ><font color='blue'><a href="JavaScript:detalle_anodos('2004-01-01','34')">Ventana</a></font></td>
				<td align='center'> 1018&nbsp</td>
				<td align='center'> 227&nbsp</td>
				<td align='center'> 6&nbsp</td>
				<td align='center'> 19&nbsp</td>
				<td align='center'> 1590&nbsp</td>
				<td align='center'> 189&nbsp</td>
				<td align='center'> 24&nbsp</td>
				<td align='center'> 147&nbsp</td>
         </tr>
         <TR class=lcol> 
				<td align='center'>06&nbsp</td>
				<td align='center'>41&nbsp</td>
				<td align='center'>Teniente&nbsp</td>
				<td align='center' ><font color='blue'><a href="JavaScript:detalle_anodos('2004-01-01','41')">Disputada</a></font></td>
				<td align='center'> 954&nbsp</td>
				<td align='center'> 43&nbsp</td>
				<td align='center'><font color='red'><strong> 22&nbsp</strong></font></td>
				<td align='center'> 5&nbsp</td>
				<td align='center'> 1655&nbsp</td>
				<td align='center'> 178&nbsp</td>
				<td align='center'><font color='red'><strong> 51&nbsp</strong></font></td>
				<td align='center'> 10&nbsp</td>
            </TR>
          </TBODY>
        </TABLE>
            </TD>
      </TR>
    </TBODY>
  </TABLE>
		   
              
  <p>&nbsp; </p>


<TABLE width="100%" align="center" cellPadding=0 cellSpacing=0 class="cm lbl">
 <TBODY>
      <TR  vAlign=top  class=dt>  
        <TD width="90%" vAlign=bottom colspan=3> <H4><B>Electrolito</B></H4></TD>
        <TD  width="10%" vAlign=bottom><div align="right"><img src="../archivos/imprimir.gif" width="26" height="18"></div></TD>
      </TR>
      <TR class=lcol vAlign=top> 
        <TD colSpan=6 bgcolor="#0066CC"> 
         <TABLE width="100%" border=0 cellPadding=2 cellSpacing=2>
          <TBODY>

            <TR class=lcol> 
                  <td width="40" align="center"><div align="center"><font size="6"><strong>CIRCUITO</strong></font></div></td>
                  <td width="40" height="63" align="center"><div align="center"><font size="6"><strong>Cu</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>H2SO4</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>As</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Sb</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Ca</strong></font></div></p>

                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Fe</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" height="3" align="center"><div align="center"><font size="6"><strong>Mg</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Ni</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Zn</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Bi</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[mg/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Pb</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[g/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Cl</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[mg/l]</strong></font></div></p></td>
                  <td width="40" align="center"><div align="center"><font size="6"><strong>Se</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[mg/l]</strong></font></div></p></td>
                  <td width="19" align="center"><div align="center"><font size="6"><strong>Te</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[mg/l]</strong></font></div></p></td>
                  <td width="19" align="center"><div align="center"><font size="6"><strong>SS</strong></font></div></p>
                    <div align="center"><font size="6"><strong>[mg/l]</strong></font></div></p></td>


            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>

            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>

            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>

            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </tr>
            <TR class=lcol> 
                <td align='center'>6&nbsp</td>
                <td align='center'>56.40&nbsp</td>
                <td align='center'>158.90&nbsp</td>
                <td align='center'>10.95&nbsp</td>
                <td align='center'>0.55&nbsp</td>
                <td align='center'>0.58&nbsp</td>
                <td align='center'>0.75&nbsp</td>
                <td align='center'>0.05&nbsp</td>
                <td align='center'>2.74&nbsp</td>
                <td align='center'>0.41&nbsp</td>
                <td align='center'>0.03 gr/lt&nbsp</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
                <td align='center'>&nbsp;</td>
             </TR>
          </TBODY>
        </TABLE>
            </TD>
      </TR>
    </TBODY>
  </TABLE>

<br>
<br>
</form>
</body>
</html>

